package com.webservice.ssdi;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebServiceClient(wsdlLocation="http://172.16.42.2:8001/soa-infra/services/ssdi/SOA_SSDI/SOA_SSDI_Service_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/SSDI_Demo/SOA_SSDI/SOA_SSDI_BPEL",
  name="SOA_SSDI_Service_ep")
public class SOA_SSDI_Service_ep
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("com.test.ssdi.SOA_SSDI_Service_ep");
      URL baseUrl = SOA_SSDI_Service_ep.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            SOA_SSDI_Service_ep.class.getResource("http://172.16.42.2:8001/soa-infra/services/ssdi/SOA_SSDI/SOA_SSDI_Service_ep?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://172.16.42.2:8001/soa-infra/services/ssdi/SOA_SSDI/SOA_SSDI_Service_ep?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://172.16.42.2:8001/soa-infra/services/ssdi/SOA_SSDI/SOA_SSDI_Service_ep?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://172.16.42.2:8001/soa-infra/services/ssdi/SOA_SSDI/SOA_SSDI_Service_ep?WSDL",
          e);
    }
  }

  public SOA_SSDI_Service_ep()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/SSDI_Demo/SOA_SSDI/SOA_SSDI_BPEL",
                    "SOA_SSDI_Service_ep"));
  }

  public SOA_SSDI_Service_ep(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="SOA_SSDI_BPEL_pt")
  public com.webservice.ssdi.SOA_SSDI_BPEL getSOA_SSDI_BPEL_pt()
  {
    return (com.webservice.ssdi.SOA_SSDI_BPEL) super.getPort(new QName("http://xmlns.oracle.com/SSDI_Demo/SOA_SSDI/SOA_SSDI_BPEL",
                                                                 "SOA_SSDI_BPEL_pt"),
                                                       com.webservice.ssdi.SOA_SSDI_BPEL.class);
  }

  @WebEndpoint(name="SOA_SSDI_BPEL_pt")
  public com.webservice.ssdi.SOA_SSDI_BPEL getSOA_SSDI_BPEL_pt(WebServiceFeature... features)
  {
    return (com.webservice.ssdi.SOA_SSDI_BPEL) super.getPort(new QName("http://xmlns.oracle.com/SSDI_Demo/SOA_SSDI/SOA_SSDI_BPEL",
                                                                 "SOA_SSDI_BPEL_pt"),
                                                       com.webservice.ssdi.SOA_SSDI_BPEL.class,
                                                       features);
  }
}
