package com.webservice.ssdi;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

public class SOA_SSDI_BPEL_ptClient
{
  @WebServiceRef
  private static SOA_SSDI_Service_ep sOA_SSDI_Service_ep;

  public static void main(String [] args)
  {
    sOA_SSDI_Service_ep = new SOA_SSDI_Service_ep();
    SOA_SSDI_BPEL sOA_SSDI_BPEL = sOA_SSDI_Service_ep.getSOA_SSDI_BPEL_pt();
    // Add your code to call the desired methods.
  }
}
