package com.test.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 22 13:23:44 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PortfolioStocksVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PortfolioStocksVOImpl() {
    }

    /**
     * Returns the bind variable value for BindPortfolioID.
     * @return bind variable value for BindPortfolioID
     */
    public Integer getBindPortfolioID() {
        return (Integer)getNamedWhereClauseParam("BindPortfolioID");
    }

    /**
     * Sets <code>value</code> for bind variable BindPortfolioID.
     * @param value value to bind as BindPortfolioID
     */
    public void setBindPortfolioID(Integer value) {
        setNamedWhereClauseParam("BindPortfolioID", value);
    }
}
