package com.test.model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Mar 23 22:42:22 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StockDetailsROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StockDetailsROVOImpl() {
    }


    /**
     * Returns the variable value for BindStockName.
     * @return variable value for BindStockName
     */
    public String getBindStockName() {
        return (String)ensureVariableManager().getVariableValue("BindStockName");
    }

    /**
     * Sets <code>value</code> for variable BindStockName.
     * @param value value to bind as BindStockName
     */
    public void setBindStockName(String value) {
        ensureVariableManager().setVariableValue("BindStockName", value);
    }

    /**
     * Returns the variable value for BindStockID.
     * @return variable value for BindStockID
     */
    public Number getBindStockID() {
        return (Number)ensureVariableManager().getVariableValue("BindStockID");
    }

    /**
     * Sets <code>value</code> for variable BindStockID.
     * @param value value to bind as BindStockID
     */
    public void setBindStockID(Number value) {
        ensureVariableManager().setVariableValue("BindStockID", value);
    }
}
