package com.test.model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 26 14:01:53 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StockPricesVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Stockid {
            public Object get(StockPricesVORowImpl obj) {
                return obj.getStockid();
            }

            public void put(StockPricesVORowImpl obj, Object value) {
                obj.setStockid((Number)value);
            }
        }
        ,
        Datetracked {
            public Object get(StockPricesVORowImpl obj) {
                return obj.getDatetracked();
            }

            public void put(StockPricesVORowImpl obj, Object value) {
                obj.setDatetracked((Number)value);
            }
        }
        ,
        Timetracked {
            public Object get(StockPricesVORowImpl obj) {
                return obj.getTimetracked();
            }

            public void put(StockPricesVORowImpl obj, Object value) {
                obj.setTimetracked((Number)value);
            }
        }
        ,
        Price {
            public Object get(StockPricesVORowImpl obj) {
                return obj.getPrice();
            }

            public void put(StockPricesVORowImpl obj, Object value) {
                obj.setPrice((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(StockPricesVORowImpl object);

        public abstract void put(StockPricesVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int STOCKID = AttributesEnum.Stockid.index();
    public static final int DATETRACKED = AttributesEnum.Datetracked.index();
    public static final int TIMETRACKED = AttributesEnum.Timetracked.index();
    public static final int PRICE = AttributesEnum.Price.index();

    /**
     * This is the default constructor (do not remove).
     */
    public StockPricesVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Price.
     * @return the Price
     */
    public Number getPrice() {
        return (Number) getAttributeInternal(PRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Price.
     * @param value value to set the  Price
     */
    public void setPrice(Number value) {
        setAttributeInternal(PRICE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Timetracked.
     * @return the Timetracked
     */
    public Number getTimetracked() {
        return (Number) getAttributeInternal(TIMETRACKED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Timetracked.
     * @param value value to set the  Timetracked
     */
    public void setTimetracked(Number value) {
        setAttributeInternal(TIMETRACKED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Stockid.
     * @return the Stockid
     */
    public Number getStockid() {
        return (Number) getAttributeInternal(STOCKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Stockid.
     * @param value value to set the  Stockid
     */
    public void setStockid(Number value) {
        setAttributeInternal(STOCKID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Datetracked.
     * @return the Datetracked
     */
    public Number getDatetracked() {
        return (Number) getAttributeInternal(DATETRACKED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Datetracked.
     * @param value value to set the  Datetracked
     */
    public void setDatetracked(Number value) {
        setAttributeInternal(DATETRACKED, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
