package com.test.model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 26 14:01:53 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StockPricesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StockPricesVOImpl() {
    }

    /**
     * Returns the bind variable value for BindStockID.
     * @return bind variable value for BindStockID
     */
    public Number getBindStockID() {
        return (Number)getNamedWhereClauseParam("BindStockID");
    }

    /**
     * Sets <code>value</code> for bind variable BindStockID.
     * @param value value to bind as BindStockID
     */
    public void setBindStockID(Number value) {
        setNamedWhereClauseParam("BindStockID", value);
    }
}
