package com.test.model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 28 13:44:23 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TestStockPricesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TestStockPricesVOImpl() {
    }

    /**
     * Returns the variable value for BindStartDate.
     * @return variable value for BindStartDate
     */
    public Number getBindStartDate() {
        return (Number)ensureVariableManager().getVariableValue("BindStartDate");
    }

    /**
     * Sets <code>value</code> for variable BindStartDate.
     * @param value value to bind as BindStartDate
     */
    public void setBindStartDate(Number value) {
        ensureVariableManager().setVariableValue("BindStartDate", value);
    }

    /**
     * Returns the variable value for BindEndDate.
     * @return variable value for BindEndDate
     */
    public Number getBindEndDate() {
        return (Number)ensureVariableManager().getVariableValue("BindEndDate");
    }

    /**
     * Sets <code>value</code> for variable BindEndDate.
     * @param value value to bind as BindEndDate
     */
    public void setBindEndDate(Number value) {
        ensureVariableManager().setVariableValue("BindEndDate", value);
    }

    /**
     * Returns the variable value for BindStockID.
     * @return variable value for BindStockID
     */
    public Number getBindStockID() {
        return (Number)ensureVariableManager().getVariableValue("BindStockID");
    }

    /**
     * Sets <code>value</code> for variable BindStockID.
     * @param value value to bind as BindStockID
     */
    public void setBindStockID(Number value) {
        ensureVariableManager().setVariableValue("BindStockID", value);
    }
}
