package com.test.model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 04 17:02:32 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserPortfolioNamesROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Portfolioname {
            public Object get(UserPortfolioNamesROVORowImpl obj) {
                return obj.getPortfolioname();
            }

            public void put(UserPortfolioNamesROVORowImpl obj, Object value) {
                obj.setPortfolioname((String)value);
            }
        }
        ,
        Portfolioid {
            public Object get(UserPortfolioNamesROVORowImpl obj) {
                return obj.getPortfolioid();
            }

            public void put(UserPortfolioNamesROVORowImpl obj, Object value) {
                obj.setPortfolioid((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(UserPortfolioNamesROVORowImpl object);

        public abstract void put(UserPortfolioNamesROVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PORTFOLIONAME = AttributesEnum.Portfolioname.index();
    public static final int PORTFOLIOID = AttributesEnum.Portfolioid.index();

    /**
     * This is the default constructor (do not remove).
     */
    public UserPortfolioNamesROVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Portfolioname.
     * @return the Portfolioname
     */
    public String getPortfolioname() {
        return (String) getAttributeInternal(PORTFOLIONAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Portfolioname.
     * @param value value to set the  Portfolioname
     */
    public void setPortfolioname(String value) {
        setAttributeInternal(PORTFOLIONAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Portfolioid.
     * @return the Portfolioid
     */
    public Number getPortfolioid() {
        return (Number) getAttributeInternal(PORTFOLIOID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Portfolioid.
     * @param value value to set the  Portfolioid
     */
    public void setPortfolioid(Number value) {
        setAttributeInternal(PORTFOLIOID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
