package com.test.model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 04 14:11:54 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserPortfoliosVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Portfolioid {
            public Object get(UserPortfoliosVORowImpl obj) {
                return obj.getPortfolioid();
            }

            public void put(UserPortfoliosVORowImpl obj, Object value) {
                obj.setPortfolioid((Number)value);
            }
        }
        ,
        Portfolioname {
            public Object get(UserPortfoliosVORowImpl obj) {
                return obj.getPortfolioname();
            }

            public void put(UserPortfoliosVORowImpl obj, Object value) {
                obj.setPortfolioname((String)value);
            }
        }
        ,
        Userid {
            public Object get(UserPortfoliosVORowImpl obj) {
                return obj.getUserid();
            }

            public void put(UserPortfoliosVORowImpl obj, Object value) {
                obj.setUserid((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(UserPortfoliosVORowImpl object);

        public abstract void put(UserPortfoliosVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PORTFOLIOID = AttributesEnum.Portfolioid.index();
    public static final int PORTFOLIONAME = AttributesEnum.Portfolioname.index();
    public static final int USERID = AttributesEnum.Userid.index();

    /**
     * This is the default constructor (do not remove).
     */
    public UserPortfoliosVORowImpl() {
    }

    /**
     * Gets UserPortfoliosEO entity object.
     * @return the UserPortfoliosEO
     */
    public EntityImpl getUserPortfoliosEO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for PORTFOLIOID using the alias name Portfolioid.
     * @return the PORTFOLIOID
     */
    public Number getPortfolioid() {
        return (Number) getAttributeInternal(PORTFOLIOID);
    }

    /**
     * Sets <code>value</code> as attribute value for PORTFOLIOID using the alias name Portfolioid.
     * @param value value to set the PORTFOLIOID
     */
    public void setPortfolioid(Number value) {
        setAttributeInternal(PORTFOLIOID, value);
    }

    /**
     * Gets the attribute value for PORTFOLIONAME using the alias name Portfolioname.
     * @return the PORTFOLIONAME
     */
    public String getPortfolioname() {
        return (String) getAttributeInternal(PORTFOLIONAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PORTFOLIONAME using the alias name Portfolioname.
     * @param value value to set the PORTFOLIONAME
     */
    public void setPortfolioname(String value) {
        setAttributeInternal(PORTFOLIONAME, value);
    }

    /**
     * Gets the attribute value for USERID using the alias name Userid.
     * @return the USERID
     */
    public Number getUserid() {
        return (Number) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as attribute value for USERID using the alias name Userid.
     * @param value value to set the USERID
     */
    public void setUserid(Number value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
