package com.test.model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 04 14:11:54 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserPortfoliosVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public UserPortfoliosVOImpl() {
    }


    /**
     * Returns the variable value for BindPortfolioName.
     * @return variable value for BindPortfolioName
     */
    public String getBindPortfolioName() {
        return (String)ensureVariableManager().getVariableValue("BindPortfolioName");
    }

    /**
     * Sets <code>value</code> for variable BindPortfolioName.
     * @param value value to bind as BindPortfolioName
     */
    public void setBindPortfolioName(String value) {
        ensureVariableManager().setVariableValue("BindPortfolioName", value);
    }

    /**
     * Returns the variable value for BindPortfolioID.
     * @return variable value for BindPortfolioID
     */
    public Number getBindPortfolioID() {
        return (Number)ensureVariableManager().getVariableValue("BindPortfolioID");
    }

    /**
     * Sets <code>value</code> for variable BindPortfolioID.
     * @param value value to bind as BindPortfolioID
     */
    public void setBindPortfolioID(Number value) {
        ensureVariableManager().setVariableValue("BindPortfolioID", value);
    }
}
