package com.proxy.ssdi;

import com.proxy.ssdi.types.ObjectFactory;
import com.proxy.ssdi.types.ServiceInput;
import com.proxy.ssdi.types.ServiceOutput;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebService(wsdlLocation="http://172.16.42.2:8001/soa-infra/services/ssdi/SOA_SSDI/SOA_SSDI_Service_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/SSDI_Demo/SOA_SSDI/SOA_SSDI_BPEL",
  name="SOA_SSDI_BPEL")
@XmlSeeAlso(
  { ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface SOA_SSDI_BPEL
{
  @WebMethod(action="process")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="process", output="http://xmlns.oracle.com/SSDI_Demo/SOA_SSDI/SOA_SSDI_BPEL/SOA_SSDI_BPEL/processResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/SSDI_Demo/SOA_SSDI/SOA_SSDI_BPEL",
    partName="payload", name="serviceOutput")
  public ServiceOutput process(@WebParam(targetNamespace="http://xmlns.oracle.com/SSDI_Demo/SOA_SSDI/SOA_SSDI_BPEL",
      partName="payload", name="serviceInput")
    ServiceInput payload);
}
